name: Jason Feng
email: jason@jason-feng.com
description: "Jason Feng's personal website"
meta_description: "Jason Feng's personal website."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: http://jason-feng.github.io
google_analytics: 'UA-61173271-1'

# Details for the RSS feed generator
url: http://jason-feng.github.io
author:         'Jason Feng'

social:
  - title: envelope
    url: mailto:jason21feng@gmail.com
  - title: github
    url: http://github.com/jason-feng
  - title: linkedin
    url: https://linkedin.com/in/jasonfeng21
  - title: twitter
    url: http://twitter.com/jasonsfeng
  - title: instagram
    url: https://instagram.com/jasonfeng_/

gems: [jekyll-paginate]
