name: Jason Feng
email: jason@jason-feng.com
description: "The personal website of Jason Feng. Visit here to check out his past work, information, and more!"
meta_description: "Jason Feng's personal website."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://jason-feng.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://jason-feng.com'
author:         'Jason Feng'
