url: https://jason-feng.github.io

# Site settings
title: Jason Feng
email: jason21feng@gmail.com
description: "The personal website of Jason Feng. Visit here to check out his past work, information, and more!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: df6161
  secondary: f28e8e
  secondary-dark: 5c5c5c

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jason-feng
  - title: linkedin
    url: https://linkedin.com/in/jasonfeng21
  - title: twitter
    url: http://twitter.com/jasonfeng_
  - title: instagram
    url: https://instagram.com/jasonfeng_/
  - title: flickr
    url: https://flic.kr/ps/2Wz3PN


# Postal address (add as many lines as necessary)
address:
  - line: Hinman Box 0160
  - line: Dartmouth College
  - line: Hanover, NH 03755

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
ga: 'UA-61173271-1'