name: Jason Feng
email: jason@jasonfeng.com
description: "A series of blog posts written by Jason Feng"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
language: 'en-us'
baseurl: /
domain_name: http://jason-feng.github.io
google_analytics: 'UA-61173271-1'

# Details for the RSS feed generator
url: http://jasonfeng.com
author: 'Jason Feng'

social:
  - title: envelope
    url: mailto:jason21feng@gmail.com
  - title: github
    url: http://github.com/jason-feng
  - title: linkedin
    url: https://linkedin.com/in/jasonfeng21
  - title: twitter
    url: http://twitter.com/jasonsfeng
  - title: instagram
    url: https://instagram.com/jasonfeng_/

gems: [jekyll-paginate]
